AllCops:
  # Use the following Exclude to prevent Rubocop from linting specific
  # directories or files.
  Exclude:
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4.1
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `-D/--display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: true

# Numbers shouldn't have to be formatted with underscores
Style/NumericLiterals:
  Enabled: false

# The excluded files below can create some pretty big blocks which are needed
Metrics/BlockLength:
  CountComments: false
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/LineLength:
  Enabled: False

Metrics/MethodLength:
  Max: 12

# This gives us some breathing room
Metrics/AbcSize:
  Max: 20

# If code isn't self-documenting then we should add documentation, otherwise
# forcing documentation isn't needed.
Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false
