language: ruby
before_script:
- cp config/database.yml.travis config/database.yml
script:
- export RAILS_ENV=test
- bundle exec rake db:setup db:migrate
- bundle exec rake spec
- bundle exec rubocop
after_success:
- if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ]; then openssl
  aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa;
  chmod 600 config/deploy_id_rsa; eval `ssh-agent -s`; ssh-add config/deploy_id_rsa;
  bundle exec cap production deploy; ssh-agent -k; fi
env:
  global:
  - secure: dwsFBQy3zOEzR82UdDcVnKx7DkmFcDF5uJDlIJPwbbMZKizfYqzdCkLvmNEYIXBSaZrJT0UD2OgGn0f/I4Sl3Xrgujq7CjEvhFKcLMpd1vLZ83LXDXNadOMsr4F/bd6nS7C3EiUcgrdLspv7VaDGjF4FqmkmxpiCBj+FVStkm5kLvgTxwMv3qT7JakshFWgO3G0OHmC+S6KNTP6admGiQzIBKJu5vQuiXWPaYvDuUs9firJjJZ+/IP+441Osx2CbvUFn11IQsFjH3A1mxQB3IH8ydkOhyRgwAgj5I/Zbf2YVupxP/sv7RliukPPgKEjRpKWH3ErQAjrqG8ylkspl1TkbSxAZ0hPYZ3Mg1bujbEZAv/s6R4g2KoOqKvAiRiKOQ6w7Lsn3qvr1s4oQJvIFMSC3L0J3L0U3cKwegSIJ+v1vYq5pp/tNO7Z4r2iPU1BQcboMBMPpRy3/7T0ACSZ5pF6Wy8IsLalQhLzASR0Qc9K0AIggKQVqzRJH6Rh7XQ/KAJWQYyT1y6Ktiee9QDTmDLRTXMOk3IQDvrs8fQ+mU0/ptQ6aEJaQx2TrI5xXUaD7tOxKiKByh13E1VZzqT5iQKxOlIRRh9te0C7FQ37Co4FqRyc2IhvPaXna8nMYN+BGJKYcjg0kGTu77j9z3Bym4zFZ9d3hrd+4jNZVVcbLImI=
  - secure: ltmSTXWAtHZkKzy9c40hZdEvgZlUjw1lIb9tv2rGUWNeR7IclafDN/m5vN5gNv/o2YUoAmdNLu0Ya0PU1ALSfTqHxw2E/ufa/N5+0AmnmSUxRYDeMFmGCAxvdlo4EZ7SSYajC3gxp+IYAlnNm97wxYI5Je7K9i5pwsG8Q86L3nyM8nmvT2ReoYyoSGRdq/qINfpAEVQdrik8kr4mpbz3yejy6w0/zHNd8XAjc30OZUXf9x5wt3vYUF6ESEmKLv7givx1dj19LkEaGB22rS2EuZgclDewoNx9RgiGT3FFUex2C4QaezRKF+Nj6uiNlRyXRsdbknd+rYdzJZcS39oD14x3SkDP0OA/ziNZX724rCdq1uaGMpttfMrI27eRcVuYtu6Cw5mzhiv5PdfIMWMjE6NRTEN2IlD5i5nyMtz0nohALJFPQjJmGCdbr/KDN3TuKFvXNd7AtQeH6BamOM3Xy+3kDgrP3pM69EuFHFMTk1k7y7cQ7+vHaW1Xh1kKEG05X3Lk6zfNCiZdYj9l+eEC27V/37aqgxe7WnHwVtnzX+QfqKcrZOyIsJqkmDKzPjkfySz60VaV/6koRtEl8TMwDIuoX6jm0Ce8T7orZOJ7ymxAM2owPGHOnkGtf7/OqZi33qPi0Achns7MhvlLFu2skx9AMtGdbBr7jnnMHcEXXcQ=
